<?php

class MySQLClientConn
{
	const COMPRESS 		= MYSQL_CLIENT_COMPRESS;
	const IGNORE_SPACE 	= MYSQL_CLIENT_IGNORE_SPACE;
	const INTERACTIVE 	= MYSQL_CLIENT_INTERACTIVE;
	const SSL 			= MYSQL_CLIENT_SSL;
}

?>